### ISSUE TITLE
NullPointerException while sending an event using Value Schema Load Generator Config

### ISSUE THREAD

**Issue by nishantworah** [corunet/kloadgen#150]
Hi,

Thank you for all the work on this plugin. Highly appreciated. We are using this plugin for  kafka load  but currently stuck with the below mentioned issue:
 
I am getting NullPointerException when I try to send an event using Value Schema Load Generator Config

2022-01-07 14:21:40,918 ERROR o.a.j.t.JMeterThread: Error while processing sampler: 'Kafka Producer Properties'.
java.lang.NullPointerException: null
	at net.coru.kloadgen.processor.AvroSchemaProcessor.createObject(AvroSchemaProcessor.java:283) ~[kloadgen-3.5.7.3-kloadgen-plugin-3.5.7.3.jar:?]
	at net.coru.kloadgen.processor.AvroSchemaProcessor.createObject(AvroSchemaProcessor.java:283) ~[kloadgen-3.5.7.3-kloadgen-plugin-3.5.7.3.jar:?]
	at net.coru.kloadgen.processor.AvroSchemaProcessor.next(AvroSchemaProcessor.java:99) ~[kloadgen-3.5.7.3-kloadgen-plugin-3.5.7.3.jar:?]
	at net.coru.kloadgen.loadgen.impl.AvroLoadGenerator.nextMessage(AvroLoadGenerator.java:60) ~[kloadgen-3.5.7.3-kloadgen-plugin-3.5.7.3.jar:?]
	at net.coru.kloadgen.sampler.KafkaSchemaSampler.runTest(KafkaSchemaSampler.java:140) ~[kloadgen-3.5.7.3-kloadgen-plugin-3.5.7.3.jar:?]
	at org.apache.jmeter.protocol.java.sampler.JavaSampler.sample(JavaSampler.java:197) ~[ApacheJMeter_java.jar:5.4.2]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:638) ~[ApacheJMeter_core.jar:5.4.2]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:558) ~[ApacheJMeter_core.jar:5.4.2]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:489) [ApacheJMeter_core.jar:5.4.2]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:256) [ApacheJMeter_core.jar:5.4.2]
	at java.lang.Thread.run(Thread.java:834) [?:?]

Thank You and Happy New Year 2022!

**Comment by kszosze** [comment]
hi @nishantworah,

I think the issue you are facing is already solved. Do you mind to try with the latest master? Actually is the 3.6.1 and you are using a 3.5.7.

Please, try with this new version.

Cheers and Happy new year 2022!!

**Comment by nishantworah** [comment]
HI @kszosze , Thank you for your help!

I updated the kloadgen version to 3.6.1 but still getting same error with latest one

022-01-10 10:54:18,534 ERROR o.a.j.t.JMeterThread: Error while processing sampler: 'Kafka Producer Properties'.
java.lang.NullPointerException: null
	at net.coru.kloadgen.processor.AvroSchemaProcessor.createObject(AvroSchemaProcessor.java:283) ~[kloadgen-3.6.1-kloadgen-plugin-3.6.1.jar:?]
	at net.coru.kloadgen.processor.AvroSchemaProcessor.createObject(AvroSchemaProcessor.java:283) ~[kloadgen-3.6.1-kloadgen-plugin-3.6.1.jar:?]
	at net.coru.kloadgen.processor.AvroSchemaProcessor.next(AvroSchemaProcessor.java:99) ~[kloadgen-3.6.1-kloadgen-plugin-3.6.1.jar:?]
	at net.coru.kloadgen.loadgen.impl.AvroLoadGenerator.nextMessage(AvroLoadGenerator.java:60) ~[kloadgen-3.6.1-kloadgen-plugin-3.6.1.jar:?]
	at net.coru.kloadgen.sampler.KafkaSchemaSampler.runTest(KafkaSchemaSampler.java:140) ~[kloadgen-3.6.1-kloadgen-plugin-3.6.1.jar:?]
	at org.apache.jmeter.protocol.java.sampler.JavaSampler.sample(JavaSampler.java:197) ~[ApacheJMeter_java.jar:5.4.2]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:638) ~[ApacheJMeter_core.jar:5.4.2]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:558) ~[ApacheJMeter_core.jar:5.4.2]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:489) [ApacheJMeter_core.jar:5.4.2]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:256) [ApacheJMeter_core.jar:5.4.2]
	at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by kszosze** [comment]
HI @nishantworah,

this is really odd, I'll check it and back to you with something asap.

Cheers

**Comment by kszosze** [comment]
Hi @nishantworah,

checking your AVRO schema definition I noticed you are defining a UNION as a type for the contactNumbers array instead of define the Record as a type. Is there a any reason for that?

Cheers!

**Comment by nishantworah** [comment]
@kszosze I would appreciate your help . Yes we need AVRO schema definition to be in this format. Thank You!

**Comment by kszosze** [comment]
@nishantworah is ok then I'll prepare some fix. But you should define then this UNION field properly as
` items: [ { .... }, null ], default : null `
or a similar type.
My advice.
Cheers!

**Comment by kszosze** [comment]
Hi @nishantworah,
I've prepared a branch with a solution to your problem. Do you mind testing it?

Cheers!

**Comment by nishantworah** [comment]
@kszosze So i can test using same AVRO schema right?

**Comment by kszosze** [comment]
Aye @nishantworah you should test with the same AVRO please.

**Comment by nishantworah** [comment]
It works now. Thank you @kszosze
